version: "3.8"

services:
  app:
    image: golang:1.18.0
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./buildkite/artifacts:/buildkite/artifacts
    entrypoint: ["./hello_binary"]
