steps:
  - label: "Build Go Application"
    plugins:
      - docker#v3.7.0:
          image: "golang:1.18.0"
          workdir: "/app"
          volumes:
            - "./hello:/app"
          command: "go build -o hello"
    artifact_paths:
      - "hello/hello"

  - block: "Enter your name"

  - label: "Run Program"
    plugins:
      - docker#v3.7.0:
          image: "alpine:latest"
          workdir: "/app"
          volumes:
            - "./hello:/app"
          command: './hello "$(buildkite-agent meta-data get name)"'
    artifact_paths:
      - "hello/hello"
