steps:
  - label: "Verify Buildkite Directory Structure"
    command:
      - "ls -R"

  - label: "Build Go Application"
    plugins:
      - docker-compose#v3.0.3:
          build: app
    artifact_paths:
      - "hello_binary"

  - block: "Pause before entering name"
    prompt: "Please enter your name in the following input step."

  - input: "Enter your name"
    fields:
      - text: "Your name"
        key: "NAME"

  - label: "Retrieve NAME"
    command: |
      echo "Retrieving NAME from metadata..."
      BUILDKITE_NAME=$(buildkite-agent meta-data get NAME || echo "DefaultName")
      buildkite-agent meta-data set BUILDKITE_NAME "$BUILDKITE_NAME"
      echo "BUILDKITE_NAME is set to: $BUILDKITE_NAME"

  - label: ":docker: Build"
    plugins:
      - docker-compose#v5.3.0:
          build: app

  - wait

  - label: "Run Hello Binary with Name"
    plugins:
      - docker-compose#v5.3.0:
          run: app
          command: ["./hello_binary", "$$BUILDKITE_NAME"]
          propagate-environment: true
