steps:
  - label: "Simple Echo"
    command: echo "Hello, Buildkite!"

  - label: "Run test script"
    command: ./test.sh

  - label: "Build Go Application"
    plugins:
      - docker#v3.7.0:
          image: "golang:1.18.0"
          workdir: "/app"
          volumes:
            - ".:/app"
          command: "go build -o hello ./hello"
    artifact_paths:
      - "hello"

  - block: "Enter your name"
    prompt: "What's your name?"

  - label: "Run Program"
    plugins:
      - docker#v3.7.0:
          image: "alpine:latest"
          workdir: "/app"
          volumes:
            - ".:/app"
          command: './hello "$(buildkite-agent meta-data get name)"'
    artifact_paths:
      - "hello"
