steps:
  - block: "Pause before entering name"
    prompt: "Please enter your name in the following input step."

  - input: "Enter your name"
    fields:
      - text: "Your name"
        key: "NAME"
        required: true

  - label: "Run Script"
    command: script.sh

  - wait: ~

  - label: "Debug NAME variable"
    command: |
      echo "All meta-data keys:"
      buildkite-agent meta-data keys
      echo "NAME from meta-data: $(buildkite-agent meta-data get NAME)"

  - label: ":docker: Build"
    plugins:
      - docker-compose#v5.3.0:
          build: app

  - wait

  # # this prints out the name - - $(buildkite-agent meta-data get NAME)
  # - label: "Debug and Run Hello Binary with Name"
  #   command:
  #     - docker-compose run --rm app $(buildkite-agent meta-data get NAME)

  - label: "Run Hello Binary with Name"
    plugins:
      - docker-compose#v5.3.0:
          run: app
          command: $(buildkite-agent meta-data get NAME
          propagate-environment: true
