steps:
  - input: "Enter your name"
    fields:
      - text: "Your name"
        key: "NAME"
        required: true

  - label: "Debug NAME variable"
    command: |
      echo "NAME from meta-data: $(buildkite-agent meta-data get NAME)"
      echo "NAME from environment: $NAME"

  - label: "Run Hello Binary with Name"
    plugins:
      - docker-compose#v3.0.3:
          run: app
          command: ["./hello_binary", "$$NAME"]
    env:
      NAME: ${NAME:-$(buildkite-agent meta-data get NAME)}
