steps:
  - label: "Verify Buildkite Directory Structure"
    command:
      - "ls -R"
  - label: "Run Hello Binary Inside Docker Container"
    plugins:
      - docker-compose#v3.0.3:
          run: app
          command: ["./hello_binary"]
