steps:
  - label: "Build Go Application"
    plugins:
      - docker#v3.7.0:
          image: "golang:1.18.0"
          workdir: "/app/hello"
          volumes:
            - ".:/app"
          command: "go build -o hello"
    artifact_paths:
      - "hello/hello"

  - block: "Enter your name"

  - label: "Run Program"
    plugins:
      - docker#v3.7.0":
          image: "alpine:latest"
          workdir: "/app/hello"
          volumes:
            - ".:/app"
          command: "./hello \"$(buildkite-agent meta-data get name)\""
    artifact_paths:
      - "hello/hello"
