steps:
  - label: "Debug Directory Structure"
    plugins:
      - docker#v5.11.0:
          image: "golang:1.18.0"
          workdir: "/app"
          volumes:
            - ".:/app"
          command:
            [
              "sh",
              "-c",
              "pwd && ls -R && echo 'Content of go.mod:' && cat go.mod",
            ]

  - label: "Build Go Application"
    plugins:
      - docker#v5.11.0:
          image: "golang:1.18.0"
          workdir: "/app"
          volumes:
            - ".:/app"
          command:
            ["sh", "-c", "go build -o hello hello.go && ./hello Buildkite"]
    artifact_paths:
      - hello

  - wait

  - label: "Run Hello Program"
    command: "./hello Buildkite"
# steps:
#   - label: "Build Go Application"
#     plugins:
#       - docker#v3.7.0:
#           image: "golang:1.18.0"
#           workdir: "/app"
#           volumes:
#             - ".:/app"
#           command:
#             - go
#             - build
#             - -o
#             - hello
#             - ./hello.go
#     artifact_paths:
#       - "hello"

#   - block: "Enter your name"
#     prompt: "What's your name?"
#     fields:
#       - text: "name"
#         key: "user-name"
#         hint: "Enter your name"

#   - label: "Run Program"
#     commands:
#       - buildkite-agent artifact download hello .
#       - chmod +x ./hello
#       - ./hello "$(buildkite-agent meta-data get user-name)"
