steps:
  - block: "Pause before entering name"
    prompt: "Please enter your name in the following input step."

  - input: "Enter your name"
    fields:
      - text: "Your name"
        key: "NAME"
        required: true

  - label: "Run Script"
    command: script.sh

  - label: "Store NAME in meta-data"
    command: |
      NAME333=$(buildkite-agent meta-data get NAME)
      echo "Storing NAME: $NAME333"
      # buildkite-agent meta-data set "stored-name" "$NAME"

  - wait: ~

  - label: "Debug NAME variable"
    command: |
      echo "All meta-data keys:"
      buildkite-agent meta-data keys
      echo "NAME from meta-data: $(buildkite-agent meta-data get NAME)"

  - label: ":docker: Build"
    plugins:
      - docker-compose#v5.3.0:
          build: app
          # command: $(buildkite-agent meta-data get NAME)

  - wait

  - label: "Debug and Run Hello Binary with Name"
    command:
      - $(buildkite-agent meta-data get NAME)

  # - label: "Debug and Run Hello Binary with Name"
  #   command: |
  #     echo "Step 1: Retrieve NAME"
  #     NAME=$(buildkite-agent meta-data get NAME)
  #     echo "Retrieved NAME: ${NAME}"

  #     echo "Step 2: Create env file"
  #     echo "BUILDKITE_NAME=${NAME}" > .env
  #     cat .env

  #     echo "Step 3: Run Docker command"
  #     docker-compose run --rm \
  #       --env-file .env \
  #       app sh -c 'echo "Inside Docker, NAME: ${BUILDKITE_NAME}" && ./hello_binary "${BUILDKITE_NAME}"'

  # - label: "Debug and Run Hello Binary with Name"
  #   command: |
  #     echo "Step 1: Retrieve NAME"
  #     echo "Raw meta-data output: $(buildkite-agent meta-data get NAME)"
  #     NAME=$(buildkite-agent meta-data get NAME)
  #     echo "Retrieved NAME: ${NAME}"

  #     echo "Step 2: Set environment variable"
  #     export BUILDKITE_NAME="${NAME}"
  #     echo "BUILDKITE_NAME: ${BUILDKITE_NAME}"

  #     echo "Step 3: Run Docker command"
  #     docker-compose run --rm \
  #       -e BUILDKITE_NAME="${BUILDKITE_NAME}" \
  #       app sh -c 'echo "Inside Docker, NAME: ${BUILDKITE_NAME}" && ./hello_binary "${BUILDKITE_NAME}"'
  # - label: "Run Hello Binary with Name"
  #   command: |
  #     export NAME=$(buildkite-agent meta-data get NAME)
  #     echo "Running Docker with NAME: ${NAME}"
  #     docker-compose run --rm -e NAME="${NAME}" app '"${NAME}"'

  # - label: "Run Hello Binary with Name"
  #   command: |
  #     NAME=$(buildkite-agent meta-data get NAME)
  #     echo "Running Docker with NAME: $NAME"
  #     # docker-compose run --rm app ./hello_binary "$NAME"
  #     # docker-compose run --rm app "$NAME"
  #     docker-compose run --rm app sh -c "\"$NAME\""

  # - label: "Run Hello Binary with Name"
  #   plugins:
  #     - docker-compose#v5.3.0:
  #         run: app
  #         # command: ["./hello_binary", "$$NAME"]
  #         command:
  #           - NAME
  #         env:
  #           - NAME=$(buildkite-agent meta-data get NAME)

  # - label: "Run Hello Binary with Name"
  #   plugins:
  #     - docker-compose#v5.3.0:
  #         run: app
  #         command: ["./hello_binary", "$$NAME"]
  #         environment:
  #           - NAME=${NAME:-$(buildkite-agent meta-data get NAME)}
  # command:
  #   [
  #     "/bin/sh",
  #     "-c",
  #     'NAME=$(buildkite-agent meta-data get NAME) && ./hello_binary "$NAME"',
  #   ]
  # propagate-environment: true
  # command:
  #   - buildkite-agent meta-data get NAME
  # propagate-environment: true

  # - label: "Run Hello Binary Directly"
  #   plugins:
  #     - docker-compose#v3.0.3:
  #         run: app
  #         propagate-environment: true
  #         command:
  #           - /app/hello_binary johnny

  # - label: "print vars"
  #   command: echo buildkite-agent meta-data keys

  # - label: "Store NAME"
  #   command: buildkite-agent meta-data set "NAME" "$(buildkite-agent meta-data get NAME)"
  # - label: "Run Hello Binary in Docker"
  #   command: |
  #     NAME=$(buildkite-agent meta-data get NAME)
  #     if [ -z "$NAME" ]; then
  #       echo "ERROR: NAME is not set in meta-data"
  #       exit 1
  #     fi
  #     echo "Running Docker with NAME: $NAME"
  #     docker-compose run --rm app ./hello_binary "$NAME"

  # - block: "Trigger another build?"
  #   prompt: "Do you want to trigger another build with the same name?"
  #   fields:
  #     - select: "Trigger build"
  #       key: "TRIGGER_BUILD"
  #       options:
  #         - label: "Yes"
  #           value: "yes"
  #         - label: "No"
  #           value: "no"

  # - label: "Trigger new build"
  #   trigger: "app-test-3"
  #   build:
  #     message: "Triggered build with NAME: ${NAME}"
  #     env:
  #       NAME: ${NAME}
  #   if: build.env.TRIGGER_BUILD == "yes"
  # - label: "Run Hello Binary with Name"
  #   command: |
  #     NAME=$(buildkite-agent meta-data get NAME)
  #     echo "Running with NAME: $NAME"
  #     docker-compose run --rm app ./hello_binary "$NAME"

  # - label: "Run Hello Binary with Name"
  #   plugins:
  #     - docker-compose#v3.0.3:
  #         run: app
  #         command: ["sh", "-c", "NAME=\"$(buildkite-agent meta-data get NAME)\" && ./hello_binary \"$NAME\""]

  # - label: "Run Hello Binary with Name"
  #   command: |
  #     NAME=$(buildkite-agent meta-data get NAME)
  #     echo "Running with NAME: $NAME"
  #     docker-compose run --rm app ./hello_binary "$NAME"
  # - label: "Run Hello Binary with Name"
  #   plugins:
  #     - docker-compose#v3.0.3:
  #         run: app
  #         command: ["./hello_binary", "$$NAME"]
  #   env:
  #     NAME: ${NAME:-$(buildkite-agent meta-data get NAME)}
