steps:
  - block: "Pause before entering name"
    prompt: "Please enter your name in the following input step."

  - input: "Enter your name"
    fields:
      - text: "Your name"
        key: "NAME"
        required: true

  - label: "Run Script"
    command: script.sh

  - label: "Debug NAME variable"
    command: |
      echo "NAME from meta-data: $(buildkite-agent meta-data get NAME)"
      echo "NAME from environment: $NAME"

  -label: "print vars"
    command: echo buildkite-agent meta-data keys


  - label: "Store NAME"
    command: buildkite-agent meta-data set "NAME" "$(buildkite-agent meta-data get NAME)"

  - label: "Run Hello Binary with Name"
    command: |
      NAME=$(buildkite-agent meta-data get "NAME")
      echo "Running with NAME: $NAME"
      docker-compose run --rm app ./hello_binary "$NAME"
  # - label: "Run Hello Binary with Name"
  #   command: |
  #     NAME=$(buildkite-agent meta-data get NAME)
  #     echo "Running with NAME: $NAME"
  #     docker-compose run --rm app ./hello_binary "$NAME"

  # - label: "Run Hello Binary with Name"
  #   plugins:
  #     - docker-compose#v3.0.3:
  #         run: app
  #         command: ["sh", "-c", "NAME=\"$(buildkite-agent meta-data get NAME)\" && ./hello_binary \"$NAME\""]

  # - label: "Run Hello Binary with Name"
  #   command: |
  #     NAME=$(buildkite-agent meta-data get NAME)
  #     echo "Running with NAME: $NAME"
  #     docker-compose run --rm app ./hello_binary "$NAME"
  # - label: "Run Hello Binary with Name"
  #   plugins:
  #     - docker-compose#v3.0.3:
  #         run: app
  #         command: ["./hello_binary", "$$NAME"]
  #   env:
  #     NAME: ${NAME:-$(buildkite-agent meta-data get NAME)}
